import { v4 } from "uuid";
import EquipmentInfoModel, {EquipmentInfoAttribute} from "../database/models/equipment_infos.model";

const entries: EquipmentInfoAttribute[] = [
    {
        id: '0ca76aa8-403c-4ba1-bd41-92893645b514',
        name: 'Can seamer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 2000,
        rent_price: 100,
        quantity: 1,
        type: 'something',
        picture:'https://www.levapack.com/wp-content/uploads/2018/10/s02-img-08.jpg',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'd57ca094-cef1-49aa-b2ae-da89653a7155',
        name: 'Pin mill',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 2500,
        rent_price: 105,
        quantity: 1,
        type: 'something',
        picture:'https://cdn.ready-market.com/101/dbd56353//Templates/pic/m/20160420-pm3-knife-type.jpg?v=601a61c6',
        rent_rate_id: 1,
        production_line_id: 2,
        available_status: true,
    },
    {
        id: '5848f071-ac20-4c54-bf73-6faeb21f5795',
        name: 'Pasta maker',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 110,
        quantity: 1,
        type: 'something',
        picture:'https://cdn11.bigcommerce.com/s-ihwnd7z21q/images/stencil/1280x1280/products/497/3561/201521_PastaMachine__79400.1642528488.jpg?c=1',
        rent_rate_id: 1,
        production_line_id: 2,
        available_status: true,
    },
    {
        id: '8d533d89-5983-4e82-b3a9-b34784c96778',
        name: 'Drum dryer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 160,
        quantity: 1,
        type: 'something',
        picture:'https://www.cimbria.com/content/dam/public/grain-and-protein/cimbria/drying/drum-dryer/dantoaster.png',
        rent_rate_id: 1,
        production_line_id: 2,
        available_status: true,
    },
    {
        id: '70d29632-634b-401a-a91b-b7e07353f19d',
        name: 'Spray dryer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 150,
        quantity: 1,
        type: 'something',
        picture:'https://www.freund-vector.com/wp-content/uploads/2021/04/VSD-800-Left-Angle-Standard-1012x1024.png',
        rent_rate_id: 1,
        production_line_id: 3,
        available_status: true,
    },
    {
        id: 'd12c2e8e-7051-4e9a-a8b8-e8d0a0dbcc29',
        name: 'Microwave vacuum dryer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://www.talinchina.com/wp-content/uploads/2022/05/microwave-vacuum-dryer-1.webp',
        rent_rate_id: 1,
        production_line_id: 3,
        available_status: true,
    },
    {
        id: '4923e8b6-0a81-4cb8-aa5f-a7e92dfb6484',
        name: 'hammer mill',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 350,
        quantity: 1,
        type: 'something',
        picture:'https://www.munsonmachinery.com/Hammer-Mills/images/Hammer-Mill_lg.png',
        rent_rate_id: 1,
        production_line_id: 4,
        available_status: true,
    },
    {
        id: '21c8ef43-db7d-4a84-ac0f-ff58d4ea5450',
        name: 'Pin mill',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 156,
        quantity: 1,
        type: 'something',
        picture:'https://image.made-in-china.com/2f0j00fvgcLljBZToN/Stainless-Steel-Powder-Making-Pin-Mill-Pulverizer-Grinding-Machine-Grinder-Pin-Pulverizer.webp',
        rent_rate_id: 1,
        production_line_id: 4,
        available_status: true,
    },
    {
        id: '288adb2d-e518-4d8a-b858-a31814ab239b',
        name: 'sausage binding',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 200,
        quantity: 1,
        type: 'something',
        picture:'https://image.made-in-china.com/44f3j00vOoHDNKRfjrG/Meat-Sausage-Fresh-Meat-Tie-Machine-Linking-Knotting-Tying-Machine-Dual-Stations-Sausage-Casing-Tying-Machine-Sausage-Binding-Machine.webp',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'c6b35eee-6260-4606-9528-1c3cd7d100a7',
        name: 'bowl chopper',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://www.superiorfoodmachinery.com/images/bowl-cutter-k15-neo-p822-4435_image.jpg',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: '7f43175e-23c2-432b-b061-a1562fd642ae',
        name: 'butter churn',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://static.wikia.nocookie.net/animalcrossing/images/a/a5/NH-DIY-Furniture-Butter_churn.png/revision/latest?cb=20200719111301',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'cc463d93-b658-4b37-b7d3-b5742d37b475',
        name: 'cream separator',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://www.thermaflo.co.nz/wp-content/uploads/2022/01/Frautech-Cream-Separator.png',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: '7f81a17f-8a30-4f5a-8020-2f45292c5435',
        name: 'ice cream maker',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://food.fnr.sndimg.com/content/dam/images/food/products/2021/4/13/rx_hamilton-beach-automatic-ice-cream-maker.jpeg.rend.hgtvcom.616.822.suffix/1618329062315.jpeg',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'cfab9fb2-86db-4f53-ab97-09f7223e726c',
        name: 'ice maker',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://intercof.co.th/cdn/shop/products/IceMakerHochizaki-KMD-201AA_1024x.jpg?v=1623817812',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: '78df8981-d732-4a21-a306-02d71d8e4835',
        name: 'food mixer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://www.airbot.co.th/cdn/shop/products/SKU-RE_1.jpg?v=1693795737&width=1024',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'd98810b8-1962-40bc-932a-87d452d688df',
        name: 'cooker-smokehouse',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://www.smokehouseproducts.com/cdn/shop/products/smokehouse-wide-gas-smoker-silver_59f3a8a4-d412-4649-9cd2-df03de6f5acb_grande.jpg?v=1548882134',
        rent_rate_id: 3,
        production_line_id: 4,
        available_status: true,
    },
    {
        id: '001c8918-4a82-4d20-82c4-ad2cd02d07a8',
        name: 'meat slicer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 250,
        quantity: 1,
        type: 'something',
        picture:'https://m.media-amazon.com/images/I/61OnesqFDhL.jpg',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
    {
        id: 'c7f5b88f-3569-4a05-b4ad-50b3df4d7794',
        name: 'dough mixer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 220,
        quantity: 1,
        type: 'something',
        picture:'https://www.ubuy.co.th/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNTF4MU94SDFpa0wuX0FDX1NMMTAwMV8uanBn.jpg',
        rent_rate_id: 4,
        production_line_id: 2,
        available_status: true,
    },
    {
        id: '4b51a07e-3932-4c8d-a579-4d3a61b28ac8',
        name: 'blender',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 50,
        quantity: 1,
        type: 'something',
        picture:'https://www.electrolux.co.th/globalassets/d2c-th/appliances/blenders/e3tb1-310k/e3tb1-310k-angl-1500x1500.png?preset=facebookthumbnail',
        rent_rate_id: 1,
        production_line_id: 3,
        available_status: true,
    },
    {
        id: '3b6587e3-27fb-4aeb-a159-9ae70c6bed50',
        name: 'viscometer',
        details: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum minus placeat molestias sunt harum distinctio facilis aperiam totam doloribus dolorem iste est, ullam fugit obcaecati doloremque excepturi commodi sequi. Assumenda.',
        average_price: 3000,
        rent_price: 180,
        quantity: 1,
        type: 'something',
        picture:'https://store.asithailand.com/wp-content/uploads/2020/05/DVE_Viscometer_2048x2048_8ed14d4c-e676-4eeb-aeb6-f248e2a808e4_1024x1024@2x.jpg',
        rent_rate_id: 1,
        production_line_id: 1,
        available_status: true,
    },
];

export const initEquipmentInfoSeed = () => EquipmentInfoModel.bulkCreate(entries);
