version: "3.9"
services:
  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    ports:
      - 3000:3000
  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080